### ISSUE TITLE
Cached regions are not explained.

### ISSUE THREAD

**Issue by BreakerSwitch** [troutspotr/troutspotr-frontend#115]
Issue Description:
 - After selecting regions on an initial load they are cached and marked with ✅, however this is not a clear designation of caching to the User.

Expected Results:
 - On the region picker, a reasonable explanation as to the presence of ✅ by regions is available.

Steps to Reproduce:
 1. Navigate to Troutspotr.
 1. Click on any state in the region selector.
 1. Click on any region within that state.
 1. Observe that the region is loaded and populated with stream data.
 1. Open the region picker.
 1. Click on the previously selected state.
 1. Observe that though the state is marked as cached, a new User would not recognize the designation as such.

**Comment by DarkNovaBlade** [comment]
This also applies to selecting a second region in a single session, though the loaded streams from the first selection are discarded, it remains marked as active.

**Comment by andest01** [comment]
I've added a header to the expanded minimap.
![chrome_2018-08-04_14-34-40](https://user-images.githubusercontent.com/1424223/43680192-09db0116-97fa-11e8-8b84-196eea7275fc.png)
