### ISSUE TITLE
There is no indication to a User when initial caching of a region is complete.

### ISSUE THREAD

**Issue by BreakerSwitch** [troutspotr/troutspotr-frontend#120]
Issue Description:
 - Following initial load, there is no indication to a User that caching is complete.

Expected Results:
 - User is alerted when caching is completed for the first time on a region.

Steps to Reproduce:
 1. Navigate to Troutspotr.
 1. Click on a state in the region picker.
 1. Click on a region in the region picker.
 1. Observe that there is no notification when loading and caching is complete.

**Comment by andest01** [comment]
I actually fucked around with this one. It became SUPER annoying (REALLY ANNOYING) to have a little Toast fly in every time you loaded and cached a new region. It was also surprisingly hard to hoist the events from deep in the bowels of an API call to the visual system.

@BreakerSwitch we need to find more subtle ways of doing this. I really like the idea, but toast was just too much.

**Comment by andest01** [comment]
Here's what I added for this ticket: 
![image](https://user-images.githubusercontent.com/1424223/43679895-7c157d9e-97f3-11e8-9560-c9776fe65793.png)

It always shows up when you """expand""" minimap.
