### ISSUE TITLE
Selected state remains on the region picker map when offline even if it lacks any cached regions.

### ISSUE THREAD

**Issue by BreakerSwitch** [troutspotr/troutspotr-frontend#122]
Issue Description:
 - If a state is selected and then internet connection is lost before any region is selected, that state remains visible on the map alongside regions with previously cached regions.

Expected Results:
 - States which have no cached regions do not appear on the region picker map while offline.

Steps to Reproduce:
 1. Navigate to Troutspotr.
 1. Click on any state in the region picker.
 1. Click on any region in the region picker.
 1. Open the region picker again.
 1. Click on a new state in the region picker.
 1. Revoke internet access.
 1. Observe that the currently selected state remains on the region picker despite being totally inaccessible.

**Comment by andest01** [comment]
![chrome_2018-07-14_13-14-41](https://user-images.githubusercontent.com/1424223/42727637-5305a598-8770-11e8-8a70-8184021d90cf.png)

**Comment by andest01** [comment]
Yeah i've decided to not fix this one. it's a bridge too far for now.
