### ISSUE TITLE
Regions are not marked on the main map

### ISSUE THREAD

**Issue by BreakerSwitch** [troutspotr/troutspotr-frontend#123]
Issue Description:
 - Regions are not displayed on the main map, making it difficult for the User to distinguish where their current dataset starts and ends.

Expected Results:
 - User can clearly tell whether a nearby area is currently displayed and labeled, not labeled, due lack of accessible streams, or due to lack of relevant data.

Steps to Reproduce:
 1. Navigate to Troutspotr.
 1. Click on any state in the region picker.
 1. Click on any region in the region picker.
 1. Observe that there is no region border for the currently selected region.

**Comment by andest01** [comment]
![image](https://user-images.githubusercontent.com/1424223/42727657-af534972-8770-11e8-9f40-9540e91c80a6.png)
