### ISSUE TITLE
State borders are not retained while offline

### ISSUE THREAD

**Issue by BreakerSwitch** [troutspotr/troutspotr-frontend#125]
Issue Description:
 - State borders are not retained while offline.

Expected Results:
 - User is able to see state borders on the main map even while offline.

Steps to Reproduce:
 1. Navigate to Troutspotr.
 1. Click on any State in the region picker.
 1. Click on any region in the region picker.
 1. Revoke internet access.
 1. Observe that state borders are removed.

Note:
 - This should also apply to region borders, when they are added.

**Comment by andest01** [comment]
BONUS: try to use the same `style` that Mapbox GL uses when online for US states so that the transition is as smooth as possible.
