### ISSUE TITLE
Wisconsin county-owned land

### ISSUE THREAD

**Issue by ghost** [troutspotr/troutspotr-frontend#150]
Look at Trimbelle Acres County Park in Pierce County Wisconsin. Technically this is public water and its actually a nice access point (never been there personally), but it doesn't show up on any GIS state-wide data set as public. Digging into it I learned that the Wisconsin state dataset lacks county-owned parcel's, such as TACP. So to be complete to capture these sites, you really need to add to the existing PAL any county owned parcel which is really time consuming and difficult. I only did it for Pierce County but it unveiled several previously unknown public sites. I believe this applies to the state of Wisconsin, just using this as an example.

**Comment by andest01** [comment]
![image](https://user-images.githubusercontent.com/1424223/46095250-b10a8a00-c181-11e8-9f07-d3761b95a16a.png)

Hunting down 72 counties is too much work, IMO. _Updating_ 72 counties _yearly_ is far far too much work.

Can you instead find some high level targets that have a wide return? Specifically those in the driftless superior that have a larger amount of pressure?

**Comment by zpope0803** [comment]
Sorry Stu, didn't see this response. I do agree that if you can't scale the operation to static and state-level, its not really scalable and not practical. IMO, any thing that requires frequent updates (>1/yr) and anything that requires county-level data management is just not practical. 

I will look more into it though. If I can find a way to apply a rule or a few rules to a state-wide dataset that covers "most" of my examples, I'll let you know. Currently I'm playing with the idea of taking the Wisconsin state parcel (V4 10.1) dataset and filtering the parcels by landowner being the county, maybe a few other flags. Getting decent results. 

Another small example is the Martell City Forest Park on the Rush. It was tough to find this one, but it does appear public. 
http://www.co.pierce.wi.us/Parks/Martell_Co_Forest/Martell%20County%20Forest%20Hike%20Map.pdf

**Comment by ghost** [comment]
I did an exercise but its incredibly tedious and the result is fragile. Probably not practical for "country-wide-scale." Stu I'm going to close this if you don't mind since I opened it.
