### ISSUE TITLE
Madison River, MT - Public water

### ISSUE THREAD

**Issue by ghost** [troutspotr/troutspotr-frontend#152]
I'm not entirely sure what the specific laws are in Montana, but I do know the land and water in and around 3-dollar bridge and Raynolds Pass are publicly accessible and widely used. There are signs that indicate which family donated between the two bridges on both sides, I believe it is inclusive of 50 ft from waters edge. Don't know if this is an official legal parcel delegation, but regardless, anglers would want to know this public access as its effectively "publicly accessible water." Might not be a dataset available to capture this though...

**Comment by andest01** [comment]
This is almost certainly an easement, which can get dicey as you move from State to State. IIRC there's another one that @WilBublitz and I fished coming out of Rock Creek Road on the upper stretches of Rock Creek, Montana. Shit, I even remember reading the memoirs of the folks who donated the "Gillies Ranch" easement. https://scholarworks.umt.edu/cgi/viewcontent.cgi?referer=https://www.google.com/&httpsredir=1&article=9567&context=etd

Again, PADUS is sort of a let down here. Montana _does_ have a reasonable level of detail for their easements: https://gis-mtfwp.opendata.arcgis.com/datasets/fwp-lands-parcels-polygons, however there's quite a bit of unknowns. Even our very own "Gillies Ranch" on Rock Creek, when non-public easements are filtered out, has a _tiny_ amount of available land.

![image](https://user-images.githubusercontent.com/1424223/45986329-7513df80-c030-11e8-9708-db6cc716e02e.png)
(red is private, green is fishable)

![image](https://user-images.githubusercontent.com/1424223/45986391-ee133700-c030-11e8-81a4-1e20004dad89.png)

**Comment by andest01** [comment]
3 buck bridge's easement is present in MT's easement data, not in PADUS. 
![image](https://user-images.githubusercontent.com/1424223/45986491-78f43180-c031-11e8-973d-32d517ff8c2f.png)

**Comment by ghost** [comment]
Alright, I think I'm officially underestimating the complexity of land rights out west with respect to streams. @andest01 you're welcome to close these as you wish, I'm just logging observations.

**Comment by ghost** [comment]
@andest01 that Madison Easement data is a little misleading though, since the stream line doesn't actually intersect the PAL polygons so in the end you'll display this as private waters without manual QGIS intervention, no? Maybe that's more of a legal question.

**Comment by andest01** [comment]
This is fine; what I'm learning is that it's better to use US State data when possible, and PADUS as a guide for what _might_ be missing.

Your observations are world a million dollars. Don't stop. This ticket won't be closed for some time, because getting the back end to get this data will be.... kinda slow.

Remember, I do this for fun. Just ask @WilBublitz, @BreakerSwitch, and @lilfisticuffer.

**Comment by andest01** [comment]
> @andest01 that Madison Easement data is a little misleading though, since the stream line doesn't actually intersect the PAL polygons so in the end you'll display this as private waters without manual QGIS intervention, no? 

Your instincts are correct -- I don't have a good way of creating river _width_, but at least people can eyeball it and put two and two together

Good news though, they'll still intersect _enough_ to draw the eye to the stream itself. Where there's a will, there's a way.

![image](https://user-images.githubusercontent.com/1424223/45986692-b7d6b700-c032-11e8-85d3-a639bd5e1b77.png)

**Comment by andest01** [comment]
lucky me, looks like i already got it.
`mt/bozeman/madison-river#nfs-route-8381@0.634`

![image](https://user-images.githubusercontent.com/1424223/45987057-1735c680-c035-11e8-9263-a2f16a37e68c.png)

But there are many more points in areas that this data will help.
