### ISSUE TITLE
Oak Creek, AZ

### ISSUE THREAD

**Issue by ghost** [troutspotr/troutspotr-frontend#154]
Not an amazing fishery, but Oak Creek and Verde around Sedona/Flagstaff do hold trout and are quite popular. Some public access too. The area is super popular in the winter with winter-flee-ers, so while its not an amazing fishery it is in high demand. Several fly shops exist in Phoenix that primarily support this area, so its probably worth displaying as a fishable trout stream. There must be some dataset out there for these? Generic link below, best I could find with a quick search.

http://sedona-arizona-vacations.com/sedona-activities/fishing-sedona/

**Comment by andest01** [comment]
The key question is "does this exists in NORWeST's Climate Change temperature models Database?"
https://www.fs.fed.us/rm/boise/AWAE/projects/NorWeST.html

If you're looking for the secret sauce that jumped this sideproject from 3 US states to 15, that's the one.

Lemmie check

**Comment by andest01** [comment]
Ah, so here's the issue. The NORWeST DB claims that the august temperatures are _well outside_ the optimized range for Brown Trout, which I have gauged to be approximately `18.8888` Celsius. 

![image](https://user-images.githubusercontent.com/1424223/45987864-67af2300-c039-11e8-9f22-a1fc9d6b1373.png)


![image](https://user-images.githubusercontent.com/1424223/45987881-7dbce380-c039-11e8-968c-69df086c670c.png)

![image](https://user-images.githubusercontent.com/1424223/45987928-ab099180-c039-11e8-9b8d-179f26b8da67.png)

@zacharyrpope not sure how we should go about resolving this one. Keep it on a errors and omissions shit-list and pull them in anyways despite the data saying it's a no?

**Comment by andest01** [comment]
A driving force behind the numbers I selected was to reduce the amount of false positives, even if it filtered out some good ones. I really wanted the data to err on the side of caution.  However, streams (and also PALs) near population centers are considered high-value targets and there are a number of folks up north near Duluth who have been wanting me to cover the city parks in Duluth for some time.

**Comment by ghost** [comment]
Hmm tough call. Pretty impressed by the rationale regardless. I think this becomes more of a business consideration based on what the given "application" is trying to accomplish. For true anglers, I'd say stick to the metric you selected, no one wants to spend time exploring the waters I mentioned in this issue, even though you may indeed find and even catch a trout or two. There is a lot of manufactured hype around these streams where tourism is high but quality is arguably low (Sedona is a great example, I'd argue the Kern CA just above that lake is another). That said, some consumer applications may want to include these streams simply because there is a market of people like myself that may find themselves in the area and really don't care that the quality isn't amazing; the fact the trout ˆmightˆ be there is reason enough for exploration and therefore should be displayed. Super tough to appeal to all use cases; I'd say stick to your rules you have and let the specific applications (like mine) deal with the details

**Comment by andest01** [comment]
Oak Creek is now available in the data set.
https://troutspotr-2018-beta.herokuapp.com/az/north-west/oak-creek
