### ISSUE TITLE
Oregon public land - state forests

### ISSUE THREAD

**Issue by zpope0803** [troutspotr/troutspotr-frontend#164]
Looks like NW Oregon is potentially missing quite a bit of public land. Specifically, the Tallimook State Forest and Caltstop State Forest are missing, which have popular streams like the Wilson River and Nehalem River. Or am I missing something?

**Comment by andest01** [comment]
You're probably right; could you do me a solid and find a dataset that has that land? Post the URL to it here when you get a chance.

**Comment by zpope0803** [comment]
K I think this is it. Adds a decent amount of public land in those state forests like Tillamook.

https://gisapps.odf.oregon.gov/data/OwnershipLandManagement.Zip

**Comment by andest01** [comment]
https://www.oregon.gov/ODF/AboutODF/Pages/MapsData.aspx

https://gisapps.odf.oregon.gov/data/metadata/LandManagementDictionary.pdf

![image](https://user-images.githubusercontent.com/1424223/48724317-83284b80-ebee-11e8-8c95-82755d0e7c2d.png)


looks like `0` and `4` are the ones we want.

**Comment by andest01** [comment]
![2018-11-19_11-34-52](https://user-images.githubusercontent.com/1424223/48724564-2711f700-ebef-11e8-9c19-85a41d6e023c.gif)


Seems legit.

**Comment by andest01** [comment]
![image](https://user-images.githubusercontent.com/1424223/50603780-47390500-0e81-11e9-8e03-777865a708cc.png)

http://cf.forestry.oregonstate.edu/sites/cf/files/Brochure%20only_0.pdf

`OSU` is off limits to fishing.

**Comment by andest01** [comment]
... and fun in general.

**Comment by andest01** [comment]
![image](https://user-images.githubusercontent.com/1424223/50607922-8c186800-0e90-11e9-925f-af265ffee156.png)


state lands have been added to the low level troutspotr postgis database but have not yet been exported officially.
