### ISSUE TITLE
Use Latest MN trout streams: adds 75+ new, removes bad streams

### ISSUE THREAD

**Issue by andest01** [troutspotr/troutspotr-frontend#168]
![image](https://user-images.githubusercontent.com/1424223/50048640-463d6080-0097-11e9-80f8-106d737e059f.png)

Red: removed
Blue: added
Black: same

💾 data here: https://gisdata.mn.gov/dataset/env-trout-stream-designations

https://www.outdoornews.com/2016/12/22/minnesota-dnr-considers-removing-trout-stream-designation-east-swan-river/

**Comment by zpope0803** [comment]
I noticed the TS streams for MN are technically different than the DNR designated streams, perhaps TS is a subset of DNR. Is there a rule/policy you use when using the DNR dataset? Like remove "Unnamed.." etc?

**Comment by andest01** [comment]
I would remove streams only when they were either a "braid" or when they were less than a mile and named "unnamed".
