### ISSUE TITLE
ENHANCEMENT: iOS/iPhone 7 - Map page: Display state names by abbreviation

### ISSUE THREAD

**Issue by alex-s-trevino** [troutspotr/troutspotr-frontend#195]
*Issue Description:*
* Right now the state names are displayed in full, which causes state names to overlap and and makes the map look cluttered.
![image1](https://user-images.githubusercontent.com/1487491/51079091-d5359c80-1686-11e9-8507-11ab501bbdf6.png)

*Recommended Result(s):*
* Display the state names by the two character abbreviations to allow for a better visual experience.

*URL(s):*
* https://troutspotr-2018-beta.herokuapp.com/

*Prereq(s):*
* n/a

*Steps To Reproduce:*
1 Navigate to https://troutspotr-2018-beta.herokuapp.com/
2 Navigate through to the map page.
3 Observe the state names overlap.

**Comment by andest01** [comment]
actually fucking good ideas ITT.
