### ISSUE TITLE
iOS CS/iPhone 7 - Map page > State View: State name and regions overlap

### ISSUE THREAD

**Issue by alex-s-trevino** [troutspotr/troutspotr-frontend#197]
*Issue Description:*
* When viewing the state view of the map, the state name is overlapped by regions.
** EX: "Idaho" is overlapped by "East Central" and "West Central".
![img_7273](https://user-images.githubusercontent.com/1487491/51079171-17131280-1688-11e9-8a95-aaf8435229e6.PNG)

*Recommended Result(s):*
* Text does not overlap.
** You could also potentially just remove the state name once you're viewing a single state.

*URL(s):*
* https://troutspotr-2018-beta.herokuapp.com/

*Prereq(s):*
* n/a

*Steps To Reproduce:*
# Navigate to https://troutspotr-2018-beta.herokuapp.com/
# Once on the map page, tap "Idaho".
# Observe "Idaho" is overlapped by "East Central" and "West Central".

**Comment by andest01** [comment]
resolved by #199

**Comment by andest01** [comment]
Region to region collisions will be tough to get, but please confirm that state names are short at the root page, and then become big once you select a state, AND state labels disappear for the specifically selected state. 

Select MN, the MN label disappears.
