### ISSUE TITLE
iOS CS/iPhone 7 - Map Page > Light Mode: Bottom border of map is black

### ISSUE THREAD

**Issue by alex-s-trevino** [troutspotr/troutspotr-frontend#206]
*Issue Description:*
* When a user views the light mode, the bottom of the map border is black.
![img_7280](https://user-images.githubusercontent.com/1487491/51080200-d4a80080-169c-11e9-9d84-35159987b7de.jpg)

*Recommended Result(s):*
* The map border is consistent colors across all four sides.

*URL(s):*
* https://troutspotr-2018-beta.herokuapp.com/

*Prereq(s):*
* n/a

*Steps To Reproduce:*
1 Navigate to https://troutspotr-2018-beta.herokuapp.com/
2 Once on the map page, tap the "Theme" toggle.
3 Observe the bottom border of the map is black, not matching the other 3 sides.

**Comment by andest01** [comment]
this drove me insane. I think I fixed this by now with an explicit `transition`
