### ISSUE TITLE
iOS CS/iPhone 7 - Stream View: The number within the "# bridges over..." text is not centered

### ISSUE THREAD

**Issue by alex-s-trevino** [troutspotr/troutspotr-frontend#209]
*Issue Description:*
* The number within the circle for the "5 bridges over publicly fishable land" text is not centered.
![img_7289](https://user-images.githubusercontent.com/1487491/51080547-4e42ed00-16a3-11e9-9cb1-1d52c781d129.jpg)

*Recommended Result(s):*
* The number is centered within the circle.

*URL(s):*
* https://troutspotr-2018-beta.herokuapp.com/or/north-east/north-fork-burnt-river

*Prereq(s):*
* n/a

*Steps To Reproduce:*
1 Navigate to https://troutspotr-2018-beta.herokuapp.com/or/north-east/north-fork-burnt-river
2 Observe the number "5" is not centered within the circle on "5 bridges over publicly fishable land" is not centered within the circle.

**Comment by andest01** [comment]
fixed and deployed.

![image](https://user-images.githubusercontent.com/1424223/53302441-a08b3800-3823-11e9-806f-cf1dfb3bb6c1.png)
