### ISSUE TITLE
TS data: road_type_id "specification"

### ISSUE THREAD

**Issue by ghost** [troutspotr/troutspotr-frontend#228]
More of a general comment/request. Underlying TS data contains some examples of type_id assignments that are not clear. One example would be the use of "road_type_id" in the roads layer, which I presume can be correlated to OSM highway_type or something like that, but it's not immediately clear what this field means. 

At some point, it would be really nice to have a readme in the dataset that defines these things.

**Comment by ghost** [comment]
Would also be nice to know which field types and data types are static, and which ones aren't guaranteed to be the same through revisions. Eg. stream_gid will change over time with each version. Will the road_id_type be global and static, or change over time?

**Comment by andest01** [comment]
@zacharyrpope 
take a look inside of `${state}.data.json` for a property called `roadTypes`. That should get you what you need.

**Comment by ghost** [comment]
@andest01 Perfect!
